// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizServer.Infrastructure.Data;

#nullable disable

namespace QuizServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301152617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizServer.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Đáp án 1 - Câu 1",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Đáp án 2 - Câu 1",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Đáp án 3 - Câu 1",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Đáp án 4 - Câu 1",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Đáp án 1 - Câu 2",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "Đáp án 2 - Câu 2",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "Đáp án 3 - Câu 2",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Đáp án 4 - Câu 2",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Đáp án 1 - Câu 3",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Đáp án 2 - Câu 3",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            Content = "Đáp án 3 - Câu 3",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "Đáp án 4 - Câu 3",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Content = "Đáp án 1 - Câu 4",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            Content = "Đáp án 2 - Câu 4",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            Content = "Đáp án 3 - Câu 4",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            Content = "Đáp án 4 - Câu 4",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "Đáp án 1 - Câu 5",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            Content = "Đáp án 2 - Câu 5",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            Content = "Đáp án 3 - Câu 5",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            Content = "Đáp án 4 - Câu 5",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 21,
                            Content = "Đáp án 1 - Câu 6",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            Content = "Đáp án 2 - Câu 6",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 23,
                            Content = "Đáp án 3 - Câu 6",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 24,
                            Content = "Đáp án 4 - Câu 6",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 25,
                            Content = "Đáp án 1 - Câu 7",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 26,
                            Content = "Đáp án 2 - Câu 7",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 27,
                            Content = "Đáp án 3 - Câu 7",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 28,
                            Content = "Đáp án 4 - Câu 7",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 29,
                            Content = "Đáp án 1 - Câu 8",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 30,
                            Content = "Đáp án 2 - Câu 8",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 31,
                            Content = "Đáp án 3 - Câu 8",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 32,
                            Content = "Đáp án 4 - Câu 8",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 33,
                            Content = "Đáp án 1 - Câu 9",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 34,
                            Content = "Đáp án 2 - Câu 9",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 35,
                            Content = "Đáp án 3 - Câu 9",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 36,
                            Content = "Đáp án 4 - Câu 9",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 37,
                            Content = "Đáp án 1 - Câu 10",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 38,
                            Content = "Đáp án 2 - Câu 10",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 39,
                            Content = "Đáp án 3 - Câu 10",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 40,
                            Content = "Đáp án 4 - Câu 10",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 41,
                            Content = "Đáp án 1 - Câu 11",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 42,
                            Content = "Đáp án 2 - Câu 11",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 43,
                            Content = "Đáp án 3 - Câu 11",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 44,
                            Content = "Đáp án 4 - Câu 11",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 45,
                            Content = "Đáp án 1 - Câu 12",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 46,
                            Content = "Đáp án 2 - Câu 12",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 47,
                            Content = "Đáp án 3 - Câu 12",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 48,
                            Content = "Đáp án 4 - Câu 12",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 49,
                            Content = "Đáp án 1 - Câu 13",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 50,
                            Content = "Đáp án 2 - Câu 13",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 51,
                            Content = "Đáp án 3 - Câu 13",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 52,
                            Content = "Đáp án 4 - Câu 13",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 53,
                            Content = "Đáp án 1 - Câu 14",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 54,
                            Content = "Đáp án 2 - Câu 14",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 55,
                            Content = "Đáp án 3 - Câu 14",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 56,
                            Content = "Đáp án 4 - Câu 14",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 57,
                            Content = "Đáp án 1 - Câu 15",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 58,
                            Content = "Đáp án 2 - Câu 15",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 59,
                            Content = "Đáp án 3 - Câu 15",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 60,
                            Content = "Đáp án 4 - Câu 15",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 61,
                            Content = "Đáp án 1 - Câu 16",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 62,
                            Content = "Đáp án 2 - Câu 16",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 63,
                            Content = "Đáp án 3 - Câu 16",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 64,
                            Content = "Đáp án 4 - Câu 16",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 65,
                            Content = "Đáp án 1 - Câu 17",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 66,
                            Content = "Đáp án 2 - Câu 17",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 67,
                            Content = "Đáp án 3 - Câu 17",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 68,
                            Content = "Đáp án 4 - Câu 17",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 69,
                            Content = "Đáp án 1 - Câu 18",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 70,
                            Content = "Đáp án 2 - Câu 18",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 71,
                            Content = "Đáp án 3 - Câu 18",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 72,
                            Content = "Đáp án 4 - Câu 18",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 73,
                            Content = "Đáp án 1 - Câu 19",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 74,
                            Content = "Đáp án 2 - Câu 19",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 75,
                            Content = "Đáp án 3 - Câu 19",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 76,
                            Content = "Đáp án 4 - Câu 19",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 77,
                            Content = "Đáp án 1 - Câu 20",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 78,
                            Content = "Đáp án 2 - Câu 20",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 79,
                            Content = "Đáp án 3 - Câu 20",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 80,
                            Content = "Đáp án 4 - Câu 20",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 81,
                            Content = "Đáp án 1 - Câu 21",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 82,
                            Content = "Đáp án 2 - Câu 21",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 83,
                            Content = "Đáp án 3 - Câu 21",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 84,
                            Content = "Đáp án 4 - Câu 21",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 85,
                            Content = "Đáp án 1 - Câu 22",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 86,
                            Content = "Đáp án 2 - Câu 22",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 87,
                            Content = "Đáp án 3 - Câu 22",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 88,
                            Content = "Đáp án 4 - Câu 22",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 89,
                            Content = "Đáp án 1 - Câu 23",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 90,
                            Content = "Đáp án 2 - Câu 23",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 91,
                            Content = "Đáp án 3 - Câu 23",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 92,
                            Content = "Đáp án 4 - Câu 23",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 93,
                            Content = "Đáp án 1 - Câu 24",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 94,
                            Content = "Đáp án 2 - Câu 24",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 95,
                            Content = "Đáp án 3 - Câu 24",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 96,
                            Content = "Đáp án 4 - Câu 24",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 97,
                            Content = "Đáp án 1 - Câu 25",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 98,
                            Content = "Đáp án 2 - Câu 25",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 99,
                            Content = "Đáp án 3 - Câu 25",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 100,
                            Content = "Đáp án 4 - Câu 25",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 101,
                            Content = "Đáp án 1 - Câu 26",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 102,
                            Content = "Đáp án 2 - Câu 26",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 103,
                            Content = "Đáp án 3 - Câu 26",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 104,
                            Content = "Đáp án 4 - Câu 26",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 105,
                            Content = "Đáp án 1 - Câu 27",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 106,
                            Content = "Đáp án 2 - Câu 27",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 107,
                            Content = "Đáp án 3 - Câu 27",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 108,
                            Content = "Đáp án 4 - Câu 27",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 109,
                            Content = "Đáp án 1 - Câu 28",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 110,
                            Content = "Đáp án 2 - Câu 28",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 111,
                            Content = "Đáp án 3 - Câu 28",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 112,
                            Content = "Đáp án 4 - Câu 28",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 113,
                            Content = "Đáp án 1 - Câu 29",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 114,
                            Content = "Đáp án 2 - Câu 29",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 115,
                            Content = "Đáp án 3 - Câu 29",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 116,
                            Content = "Đáp án 4 - Câu 29",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 117,
                            Content = "Đáp án 1 - Câu 30",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 118,
                            Content = "Đáp án 2 - Câu 30",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 119,
                            Content = "Đáp án 3 - Câu 30",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 120,
                            Content = "Đáp án 4 - Câu 30",
                            IsCorrect = false,
                            OrderIndex = 4,
                            QuestionId = 30
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Dimensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chương đại số",
                            Name = "Đại số",
                            SubjectId = 1,
                            Type = "Group"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chương hình học",
                            Name = "Hình học",
                            SubjectId = 1,
                            Type = "Group"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chương cơ học",
                            Name = "Cơ học",
                            SubjectId = 2,
                            Type = "Group"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chương điện từ",
                            Name = "Điện từ",
                            SubjectId = 2,
                            Type = "Group"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chương hóa vô cơ",
                            Name = "Hóa vô cơ",
                            SubjectId = 3,
                            Type = "Group"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("QuizTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizTemplateId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bài 1: Số phức",
                            OrderIndex = 1,
                            Status = "Active",
                            SubjectId = 1,
                            Type = "Lesson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bài 2: Hàm số",
                            OrderIndex = 2,
                            QuizTemplateId = 1,
                            Status = "Active",
                            SubjectId = 1,
                            Type = "Lesson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bài 1: Động học",
                            OrderIndex = 1,
                            Status = "Active",
                            SubjectId = 2,
                            Type = "Lesson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bài 2: Động lực học",
                            OrderIndex = 2,
                            QuizTemplateId = 2,
                            Status = "Active",
                            SubjectId = 2,
                            Type = "Lesson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bài 1: Bảng tuần hoàn",
                            OrderIndex = 1,
                            QuizTemplateId = 3,
                            Status = "Active",
                            SubjectId = 3,
                            Type = "Lesson"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BriefInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BriefInfo = "Hệ thống ôn tập trắc nghiệm trực tuyến",
                            Category = "Tin tức",
                            Content = "Nội dung bài viết...",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            Status = "Active",
                            Title = "Giới thiệu hệ thống ôn tập",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BriefInfo = "Lịch thi thử các môn",
                            Category = "Sự kiện",
                            Content = "Nội dung...",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = false,
                            Status = "Active",
                            Title = "Lịch thi thử tháng 1",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BriefInfo = "Hướng dẫn chi tiết",
                            Category = "Hướng dẫn",
                            Content = "Nội dung...",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            Status = "Active",
                            Title = "Hướng dẫn sử dụng",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.PricePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("PricePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Truy cập 1 tháng",
                            DurationMonths = 1,
                            ListPrice = 100000m,
                            Name = "Gói 1 tháng",
                            SalePrice = 80000m,
                            Status = "Active",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Truy cập 3 tháng - tiết kiệm 20%",
                            DurationMonths = 3,
                            ListPrice = 250000m,
                            Name = "Gói 3 tháng",
                            SalePrice = 200000m,
                            Status = "Active",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Truy cập 1 tháng",
                            DurationMonths = 1,
                            ListPrice = 100000m,
                            Name = "Gói 1 tháng",
                            SalePrice = 90000m,
                            Status = "Active",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Truy cập 1 tháng",
                            DurationMonths = 1,
                            ListPrice = 100000m,
                            Name = "Gói 1 tháng",
                            SalePrice = 85000m,
                            Status = "Active",
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DimensionId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Câu hỏi mẫu 1 - Môn 1",
                            DimensionId = 1,
                            Explanation = "Giải thích đáp án câu 1",
                            Level = 0,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Câu hỏi mẫu 2 - Môn 1",
                            DimensionId = 1,
                            Explanation = "Giải thích đáp án câu 2",
                            Level = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Câu hỏi mẫu 3 - Môn 1",
                            DimensionId = 1,
                            Explanation = "Giải thích đáp án câu 3",
                            Level = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Câu hỏi mẫu 4 - Môn 1",
                            DimensionId = 1,
                            Explanation = "Giải thích đáp án câu 4",
                            Level = 0,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Câu hỏi mẫu 5 - Môn 1",
                            DimensionId = 1,
                            Explanation = "Giải thích đáp án câu 5",
                            Level = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Câu hỏi mẫu 6 - Môn 1",
                            DimensionId = 2,
                            Explanation = "Giải thích đáp án câu 6",
                            Level = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Câu hỏi mẫu 7 - Môn 1",
                            DimensionId = 2,
                            Explanation = "Giải thích đáp án câu 7",
                            Level = 0,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Câu hỏi mẫu 8 - Môn 1",
                            DimensionId = 2,
                            Explanation = "Giải thích đáp án câu 8",
                            Level = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Câu hỏi mẫu 9 - Môn 1",
                            DimensionId = 2,
                            Explanation = "Giải thích đáp án câu 9",
                            Level = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Câu hỏi mẫu 10 - Môn 1",
                            DimensionId = 2,
                            Explanation = "Giải thích đáp án câu 10",
                            Level = 0,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Câu hỏi mẫu 1 - Môn 2",
                            DimensionId = 3,
                            Explanation = "Giải thích đáp án câu 1",
                            Level = 0,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 12,
                            Content = "Câu hỏi mẫu 2 - Môn 2",
                            DimensionId = 3,
                            Explanation = "Giải thích đáp án câu 2",
                            Level = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 13,
                            Content = "Câu hỏi mẫu 3 - Môn 2",
                            DimensionId = 3,
                            Explanation = "Giải thích đáp án câu 3",
                            Level = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 14,
                            Content = "Câu hỏi mẫu 4 - Môn 2",
                            DimensionId = 3,
                            Explanation = "Giải thích đáp án câu 4",
                            Level = 0,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Câu hỏi mẫu 5 - Môn 2",
                            DimensionId = 3,
                            Explanation = "Giải thích đáp án câu 5",
                            Level = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 16,
                            Content = "Câu hỏi mẫu 6 - Môn 2",
                            DimensionId = 4,
                            Explanation = "Giải thích đáp án câu 6",
                            Level = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 17,
                            Content = "Câu hỏi mẫu 7 - Môn 2",
                            DimensionId = 4,
                            Explanation = "Giải thích đáp án câu 7",
                            Level = 0,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 18,
                            Content = "Câu hỏi mẫu 8 - Môn 2",
                            DimensionId = 4,
                            Explanation = "Giải thích đáp án câu 8",
                            Level = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 19,
                            Content = "Câu hỏi mẫu 9 - Môn 2",
                            DimensionId = 4,
                            Explanation = "Giải thích đáp án câu 9",
                            Level = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 20,
                            Content = "Câu hỏi mẫu 10 - Môn 2",
                            DimensionId = 4,
                            Explanation = "Giải thích đáp án câu 10",
                            Level = 0,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 21,
                            Content = "Câu hỏi mẫu 1 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 1",
                            Level = 0,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 22,
                            Content = "Câu hỏi mẫu 2 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 2",
                            Level = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 23,
                            Content = "Câu hỏi mẫu 3 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 3",
                            Level = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 24,
                            Content = "Câu hỏi mẫu 4 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 4",
                            Level = 0,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 25,
                            Content = "Câu hỏi mẫu 5 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 5",
                            Level = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 26,
                            Content = "Câu hỏi mẫu 6 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 6",
                            Level = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 27,
                            Content = "Câu hỏi mẫu 7 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 7",
                            Level = 0,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 28,
                            Content = "Câu hỏi mẫu 8 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 8",
                            Level = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 29,
                            Content = "Câu hỏi mẫu 9 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 9",
                            Level = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 30,
                            Content = "Câu hỏi mẫu 10 - Môn 3",
                            DimensionId = 5,
                            Explanation = "Giải thích đáp án câu 10",
                            Level = 0,
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("QuizTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizTemplateId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScorePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.QuizTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PassRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("QuizTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 20,
                            Level = 1,
                            Name = "Đề thi thử Toán 15 câu",
                            PassRate = 60m,
                            QuestionCount = 15,
                            SubjectId = 1,
                            Type = "Simulation"
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 25,
                            Level = 1,
                            Name = "Đề thi thử Vật lý 20 câu",
                            PassRate = 60m,
                            QuestionCount = 20,
                            SubjectId = 2,
                            Type = "Simulation"
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 15,
                            Level = 0,
                            Name = "Bài tập Hóa 10 câu",
                            PassRate = 70m,
                            QuestionCount = 10,
                            SubjectId = 3,
                            Type = "LessonQuiz"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sale"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tên website",
                            Order = 1,
                            Status = "Active",
                            Type = "SiteName",
                            Value = "Quiz Practicing System"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Email liên hệ",
                            Order = 2,
                            Status = "Active",
                            Type = "ContactEmail",
                            Value = "support@quiz.com"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Số điện thoại",
                            Order = 3,
                            Status = "Active",
                            Type = "ContactPhone",
                            Value = "1900xxxx"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Backlink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Backlink = "/subjects",
                            ImageUrl = "/images/banner1.jpg",
                            Notes = "Banner chính",
                            Status = "Active",
                            Title = "Banner chào mừng"
                        },
                        new
                        {
                            Id = 2,
                            Backlink = "/subjects",
                            ImageUrl = "/images/banner2.jpg",
                            Notes = "Khuyến mãi",
                            Status = "Active",
                            Title = "Khuyến mãi tháng 1"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Khoa học tự nhiên",
                            Description = "Môn Toán cao cấp",
                            IsFeatured = true,
                            Name = "Toán học",
                            OwnerId = 2,
                            Status = "Published",
                            TagLine = "Ôn tập Toán hiệu quả",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Khoa học tự nhiên",
                            Description = "Môn Vật lý đại cương",
                            IsFeatured = true,
                            Name = "Vật lý",
                            OwnerId = 2,
                            Status = "Published",
                            TagLine = "Luyện Vật lý từ cơ bản",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Khoa học tự nhiên",
                            Description = "Môn Hóa học hữu cơ",
                            IsFeatured = false,
                            Name = "Hóa học",
                            OwnerId = 2,
                            Status = "Published",
                            TagLine = "Hóa học dễ hiểu",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.SubjectRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePackageId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PricePackageId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("SubjectRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PricePackageId = 1,
                            SaleId = 4,
                            Status = "Paid",
                            SubjectId = 1,
                            TotalCost = 80000m,
                            UserId = 5,
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PricePackageId = 3,
                            Status = "Submitted",
                            SubjectId = 2,
                            TotalCost = 90000m,
                            UserId = 5,
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FullName = "Administrator",
                            PasswordHash = "$2a$11$nTuecSCNv88haB9/Dh15WeSpIp/ya7AMvqINgAOQlSB.NBWoE6IYW",
                            RoleId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "expert@gmail.com",
                            FullName = "Expert User",
                            PasswordHash = "$2a$11$nTuecSCNv88haB9/Dh15WeSpIp/ya7AMvqINgAOQlSB.NBWoE6IYW",
                            RoleId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marketing@gmail.com",
                            FullName = "Marketing User",
                            PasswordHash = "$2a$11$nTuecSCNv88haB9/Dh15WeSpIp/ya7AMvqINgAOQlSB.NBWoE6IYW",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sale@gmail.com",
                            FullName = "Sale User",
                            PasswordHash = "$2a$11$nTuecSCNv88haB9/Dh15WeSpIp/ya7AMvqINgAOQlSB.NBWoE6IYW",
                            RoleId = 4,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@gmail.com",
                            FullName = "Sample Customer",
                            PasswordHash = "$2a$11$nTuecSCNv88haB9/Dh15WeSpIp/ya7AMvqINgAOQlSB.NBWoE6IYW",
                            RoleId = 5,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuizResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizResultId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Answer", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Dimension", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("Dimensions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.QuizTemplate", "QuizTemplate")
                        .WithMany()
                        .HasForeignKey("QuizTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizTemplate");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.PricePackage", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("PricePackages")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Question", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Dimension", "Dimension")
                        .WithMany("Questions")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dimension");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.QuizTemplate", "QuizTemplate")
                        .WithMany()
                        .HasForeignKey("QuizTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("Quizzes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizServer.Domain.Entities.User", "User")
                        .WithMany("Quizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizTemplate");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.QuizResult", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizResults")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Domain.Entities.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.QuizTemplate", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("QuizTemplates")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Subject", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.SubjectRegistration", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.PricePackage", "PricePackage")
                        .WithMany("Registrations")
                        .HasForeignKey("PricePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizServer.Domain.Entities.Subject", "Subject")
                        .WithMany("Registrations")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizServer.Domain.Entities.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PricePackage");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.User", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("QuizServer.Domain.Entities.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizServer.Domain.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizServer.Domain.Entities.QuizResult", "QuizResult")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuizResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Dimension", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.PricePackage", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.QuizResult", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("Lessons");

                    b.Navigation("PricePackages");

                    b.Navigation("Questions");

                    b.Navigation("QuizTemplates");

                    b.Navigation("Quizzes");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("QuizServer.Domain.Entities.User", b =>
                {
                    b.Navigation("QuizResults");

                    b.Navigation("Quizzes");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
